### ISSUE TITLE
[SP2019]Test kit

### ISSUE THREAD

**Issue by JennyLouise** [sourcebots/tasks#118]
Checking boards are working

**Comment by kierdavis** [comment]
The power and motor boards were tested a few weeks ago; their "working" status in the inventory is up to date.

Servo boards (and probably some more power and motor boards) will be coming on loan from SR; if they haven't tested them already, we should.

I think all the motors have been tested recently, but that isn't something I've been involved in.

Raspberry Pis should definitely be tested. It's probably a good idea to check the webcams and USB hubs too.

Anything else?

**Comment by joe9599** [comment]
I can confirm that the motors were tested

**Comment by trickeydan** [comment]
@PeterJCLaw @kierdavis 

To my understanding you are handling the SR side of providing the kit. Are you planning to test the kit beforehand?

**Comment by PeterJCLaw** [comment]
> @PeterJCLaw @kierdavis
> 
> To my understanding you are handling the SR side of providing the kit. Are you planning to test the kit beforehand?

This is new to me.

**Comment by trickeydan** [comment]
In that case, we should assume that SR are not testing and haven't tested the kit until we hear otherwise.

**Comment by PeterJCLaw** [comment]
> In that case, we should assume that SR are not testing and haven't tested the kit until we hear otherwise.

The loan agreement is pretty clear that the kit should be considered as being in an unknown state.

That said, I happen to know that a lot of the kit we'll be using has been tested. Some of the parts I'm suggesting that we borrow have been tested since SR2019, others were tested before that and not shipped. The latter have been in storage for ~10 months, but I think that's probably ok.
(I've a document with notes on this which I've shared in Slack but am deliberately not posting here)

**Comment by kierdavis** [comment]
Power boards are being tested.

**Comment by kierdavis** [comment]
Power boards have been tested. All that's left is to do a quick check that every Pi boots, once its SD card has been flashed (#181).

**Comment by kierdavis** [comment]
Everything left to do on this is a "SHOULD".

**Comment by kierdavis** [comment]
Testing Pis can't be done until the SD cards are flashed on Monday morning, updating milestone.

**Comment by PeterJCLaw** [comment]
The kits are in use. I don't think this adds a lot now.
