### ISSUE TITLE
[SP2019]Pack team kits

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#119]

**Comment by joe9599** [comment]
worst case can we put things on the big table, and they collect it

**Comment by RealOrangeOne** [comment]
We probably need a list of things we need to be put in kits _before_ we pack them

**Comment by RealOrangeOne** [comment]
## Camcons

- 2 large
- 3 medium
- 2 small

**Comment by kierdavis** [comment]
Kit status (will be kept up to date as things change):

Tick when item has been put into every kit RUB.

* [x] Pi assembly: these need to be tested as a whole (#118)
  * Raspberry Pi: these are in the kit boxes but should be tested as mentioned above
  * Power hat: these are attached to the Pis
  * Micro SD card: these are *not* in the kit boxes since they need to be flashed (#181)
* [x] Power board assembly: packed
  * Power board (from SR): packed
  * 5mm camcon jumper: attached to power boards
* [x] Motor board (from SR): packed
* [x] Servo board (from SR): packed
* [x] Arduino assembly: packed
  * Arduino: packed
  * Arduino header shield, USB side: attached to arduinos
  * Arduino header shield, power side: attached to arduinos
* [x] USB hub: packed
* [x] USB stick x 2: packed
* [x] Micro USB cable x 3: packed
* [x] Not-micro USB cable: packed
* [x] Camcon bag: packed
  * 7.5mm camcon x 4
  * 5mm camcon x 4
  * 3.81mm camcon x 2
* [x] Sensor bag: packed
  * Ultrasound sensor x 2
  * Microswitch x 4
* [x] Toolkit: packed
* [x] Motor x 2: packed
* [x] Flag mount: packed

**Comment by kierdavis** [comment]
@RealOrangeOne I don't think those camcon quantities are correct, please see sourcebots/sbot#46 for what I think they should be and why.

**Comment by kierdavis** [comment]
Kits have been packed as best we can right now, and their contents double-checked. They are currently missing SD cards, motors and flag mounts.

What still needs to be done:

* [ ] Flash the SD cards (#181), put one in each Pi, and check it boots.
* [x] Retrieve the motors from B16 and put two in each box.
* [x] Find the flag mounts (accidentally taken to B16 with the motors) and put one in each box.

**Comment by kierdavis** [comment]
Nothing else we can do on this today, updating milestone.

**Comment by sedders123** [comment]
We are waiting on access to the 'big flashing gadget' in the lab technicians office to flash multiple cards at once.

**Comment by kierdavis** [comment]
SD cards flashed. I need to put them in the Pis and briefly test them, then this can be considered complete.

**Comment by kierdavis** [comment]
Inserted into Pis and checked there is activity on the LEDs when the boot. Not a brilliant test but we didn't have an HDMI cable to hand. We'll discover any actual issues once the teams start trying to use them in robots.

This is now complete.
