### ISSUE TITLE
[SP2019]Validate electronics labs

### ISSUE THREAD

**Issue by RealOrangeOne** [sourcebots/tasks#185]
General polishing etc.

**Comment by joe9599** [comment]
This has already been done, @Dasepho and I have reviewed the labs since recent changes by Jon Bartlett, we do however need to figure out who is leading the labs, from discussion with @Adimote it was believed that it was me and @Dasepho, however I have also since heard that @Tyler-Ward and Jon Bartlett are leading it

**Comment by kierdavis** [comment]
This is pretty much done, Dan H is going to print a fresh copy for proofreading and than that's it.

**Comment by Dasepho** [comment]
Done
