### ISSUE TITLE
[SP2019]Archive SP2019 Floorplan

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#192]
We should add them to https://github.com/sourcebots/floorplan

**Comment by kierdavis** [comment]
Although I know this issue refers to the various SUSU venues, we should also archive the L2 labs layout because right now it's only stored in Slack (which means it will disappear in a few months).

I've attached it here: [Smallpeice 2019.pdf](https://github.com/sourcebots/tasks/files/3619470/Smallpeice.2019.pdf)

**Comment by trickeydan** [comment]
> Although I know this issue refers to the various SUSU venues, we should also archive the L2 labs layout because right now it's only stored in Slack (which means it will disappear in a few months).
> 
> I've attached it here: [Smallpeice 2019.pdf](https://github.com/sourcebots/tasks/files/3619470/Smallpeice.2019.pdf)

Added to kb https://github.com/roboticsoutreach/kb/pull/10

**Comment by kierdavis** [comment]
Although we've added the floorplan for labs, I don't think we have the one for SUSU (unless I'm being blind). Opened https://github.com/roboticsoutreach/kb/issues/33 to track this.
