### ISSUE TITLE
Finish assembling power boards

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#209]

**Comment by kierdavis** [comment]
There's quite a bit more to it than purely the press-fit connectors.

Each power board requires:

* a piezo buzzer (Mouser 81-PKM13EPYH4000-A0) if it doesn't have one already - Beta were unclear on whether they were actually going to mount it or not because it prevents access to the components beneath it
* three press-fit connectors (Farnell 1821273) for mounting the fuse and captive cables
* three M5x6mm machine screws (Farnell 149483) for the above connectors
* three M5 spring washers (Farnell 2506046) for the above connectors
* a 40A midi fuse (Mouser 576-0498040.M)
* two captive cables: sturdy wires, capable of 40A, terminated at one end with M5 ring terminals (Farnell 2310102) and at the other with a male XT60 (Hobbytronics PRT-10474)
* a 40mm fan (Mouser 670-OD4010-12HSS)
* two M3x16mm machine screws (Farnell 7071000) for mounting the fan
* two M3 nylon washers (Farnell 2472664) for mounting the fan
* two M3 nuts (Farnell 7016943) for mounting the fan
* two M3x8mm bushings (Farnell 891435) for mounting the fan
* a red button cap (Mouser 611-PVRD) for the power button
* a black button cap (Mouser 611-PVBK) for the start button

This info was pulled from the [BOM from the 2017 kit run](https://docs.google.com/spreadsheets/d/1UovAPckLQV8dIVhT-7f81d5N7fylY4sFi6lWpsmIKw8/edit#gid=0) and [list of additional items](https://docs.google.com/spreadsheets/d/1FpHHEBVmIX3i9QIH4J0oXq1S2dJI_CUtUEvBDnSF-Fk/edit#gid=0).

**Comment by trickeydan** [comment]
> a piezo buzzer (Mouser 81-PKM13EPYH4000-A0) if it doesn't have one already - Beta were unclear on whether they were actually going to mount it or not because it prevents access to the components beneath it

These are present.

**Comment by tpoomlmly** [comment]
Also done (for SP2023)
