### ISSUE TITLE
Investigate replacement USB Cables

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#218]
The USB Cables we had last year caused lots of issues.

We need ones with decent shielding.

**Comment by nmalky** [comment]
I have had good experiences (personal, not for robotics or at competition scale) with Anker cables - they are quite thick/well-made. I have put some with calculations in the order spreadsheet.

There may be some other sources of cables e.g. AmazonBasics or another brand from another source, but I don't have experience with these. Anker also comes with 18 month warranty; if cables break before the competition, it should be possible to get replacements.

Of course, we still need to have spares available.

Do we have an idea of quantities needed for each length? What components do the cables need to connect together on the robots?

With 16 teams, we can afford (using Anker PowerLine cables as a baseline)
- 1x 6ft/1.8m cable at ~£4/cable
- 2x 3ft/0.9m cable at ~£2.33/cable
- 1x 1ft/0.3m cable at ~£1.75/cable
per team

Buying in a pack of 6 (https://www.amazon.co.uk/Anker-6-Pack-PowerLine-Micro-USB/dp/B016BF4I5K) gets us an additional 3ft cable + 1ft cable for free (~£9.99/pack). These could be kept as spares? (16 spare 3ft cables, 16 spare 1ft cables). This leaves some extra room for buying spare 6ft cables; the ratios can be adjusted by buying fewer packs of 6.

This is just an example; I don't know how well these Anker cables would hold up in a competition environment. The Amazon reviews aren't *all* positive, but having spares (as an organisation) + the teams each having a spare cable + 18 month warranty in which we could batch-replace defective/damaged cables should account for this - I hope?

We should maybe compare these against other options (and the cables we had last year), also accounting for price / general durability / warranty.

Do we have a way of testing/quantifying how well-shielded cables actually are? (So that we can compare against competing options)

Do the USB ports on our boards have any nonstandard dimensions? (i.e. does it matter if the micro B connector is slightly larger than standard? or slightly smaller?) Did we have any problems with overly loose/tight connections last year? (From reviews, Anker has slightly larger connectors whereas AmazonBasics apparently tries to be smaller, but this needs actual measurement.)

etc.

**Comment by nmalky** [comment]
Article on checking shielding, for reference: https://www.yoctopuce.com/EN/article/usb-cables-shielding-matters-as-well

**Comment by trickeydan** [comment]
We have added one pack of these onto Order 2.

**Comment by trickeydan** [comment]
Blocked on arrival of Order 2

**Comment by tpoomlmly** [comment]
Order 2 has arrived, but not been unboxed yet
