### ISSUE TITLE
[SP2019]Arrange for prizes

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#27]

**Comment by joe9599** [comment]
is this trophies/certificates or something more "interesting" i think in my year it was drones, it could be an electronics kit or a pi, does anyone have any strong feelings about what prizes should be
Is this just for 1st or 1st, 2nd, 3rd (in which case we would also need to organise a 3rd/4th playoff

**Comment by trickeydan** [comment]
I believe Smallpeice is 1st, 2nd, 3rd, committee.

Not trophies. Usually things like drones, or robot kits.

> in which case we would also need to organise a 3rd/4th playoff

That will be handled by scheduling, or deferred to league points.

**Comment by jcwilliamson** [comment]
I believe we did drones and arduino starter kit things last year.

**Comment by joe9599** [comment]
do we usually order something, or approach companies and ask them to support us.
I prefer the idea of a kit rather than something like a drone, but if that has been successful in the past then I'm not going to disagree. do we have a rough budget for this

**Comment by joe9599** [comment]
Here are a few quick options from amazon, however its hard to do much on this without having any information about budget
https://www.amazon.co.uk/SIMREX-Foldable-Quadcopter-Headless-Altitude/dp/B07J4VLR7S/ref=sr_1_6?keywords=drone&qid=1561814487&s=gateway&sr=8-6
https://www.amazon.co.uk/H6-Foldable-Altitude-Quadcopter-One-Button/dp/B075XHV1S5/ref=sr_1_7?keywords=drone&qid=1561814487&s=gateway&sr=8-7
https://www.amazon.co.uk/Elegoo-Project-Starter-Tutorial-Arduino/dp/B01D8KOZF4/ref=sr_1_1_sspa?crid=2W3UENG3J3XT7&keywords=arduino+starter+kit&qid=1561814542&s=gateway&sprefix=arduino+%2Caps%2C138&sr=8-1-spons&psc=1

Or we could go for a raspberry pi 4, but would likely also need to supply a power lead and at least 1 display lead, due to power issues, and the display output being much less common that before (it is no longer HDMI)

**Comment by joe9599** [comment]
last years budget was ~£400
if we were to do raspberry pi 4 (1GB with a power cable and a micro HDMI cable) would cost £47 per person so would only leave ~£165 for 2nd and 3rd, I dont know what the split between 1st 2nd and 3rd has been in previous years, but this doesnt seem too unreasonable

**Comment by Tyler-Ward** [comment]
Added to order list 5
