### ISSUE TITLE
[SP2019]Decide the best way to construct the tree

### ISSUE THREAD

**Issue by Dasepho** [sourcebots/tasks#73]
Game requires a 'tree' in the centre of the arena to attach 'Golden Apples' to. Idea is to use [this](https://eclipsestagingservices.ae/service-catalogue/staging-services/rigging/truss-accessories/truss-x-base-black/c-23/c-139/p-575) truss stand and staging equipment then make it look pretty.

**Comment by WillB97** [comment]
We could build this using a length of Susu(#85) truss stood upright in an Xbase with scaffold poles for the branches.

Since this can be made entirely from Susu equipment this seems like a simple solution. We can rap it in cloth like the arena.

Susu has a range of scaff pole lengths so we should figure out approximately how long we'd want, we will likely need to provide caps for the end of the poles for safety.

**Comment by joe9599** [comment]
How will the cubes attach to this? velcro?

**Comment by WillB97** [comment]
For the final attachment velcro-ing the cubes would probably be best.

I'm not sure how well velcro-ing directly to the scaffold pole would work since your trying to join a flat and a round object.

Probably putting velcro onto a scaffold mount would work best, I'll have to check next time I'm in soton.

**Comment by joe9599** [comment]
not doing apple tree
